linters:

	BangFormat:
		enabled: true
		space_before_bang: true
		space_after_bang: false

	BorderZero:
		enabled: true

	ColorKeyword:
		enabled: true

	ColorVariable:
		enabled: false

	Comment:
		enabled: false

	DebugStatement:
		enabled: true

	DeclarationOrder:
		enabled: true

	DuplicateProperty:
		enabled: true

	ElsePlacement:
		enabled: true
		style: same_line

	EmptyLineBetweenBlocks:
		enabled: true
		ignore_single_line_blocks: false

	EmptyRule:
		enabled: true

	FinalNewline:
		enabled: true
		present: true

	HexLength:
		enabled: true
		style: short

	HexNotation:
		enabled: true
		style: lowercase

	HexValidation:
		enabled: true

	IdSelector:
		enabled: true

	ImportantRule:
		enabled: true

	ImportPath:
		enabled: true
		leading_underscore: false
		filename_extension: false

	Indentation:
		enabled: true
		character: space
		width: 4

	LeadingZero:
		enabled: true
		style: exclude_zero

	MergeableSelector:
		enabled: true

	NameFormat:
		enabled: false
		convention: hyphenated_lowercase

	NestingDepth:
		enabled: true
		max_depth: 4

	PlaceholderInExtend:
		enabled: true

	PropertyCount:
		enabled: false

	PropertySortOrder:
		enabled: false

	PropertySpelling:
		enabled: true
		extra_properties: []

	QualifyingElement:
		enabled: true
		allow_element_with_attribute: false
		allow_element_with_class: false
		allow_element_with_id: false

	SelectorDepth:
		enabled: true
		max_depth: 3

	SelectorFormat:
		enabled: true
		convention: hyphenated_lowercase

	Shorthand:
		enabled: true

	SingleLinePerProperty:
		enabled: true
		allow_single_line_rule_sets: true

	SingleLinePerSelector:
		enabled: false

	SpaceAfterComma:
		enabled: true

	SpaceAfterPropertyColon:
		enabled: true
		style: one_space

	SpaceAfterPropertyName:
		enabled: true

	SpaceBeforeBrace:
		enabled: true
		style: space
		allow_single_line_padding: true

	SpaceBetweenParens:
		enabled: false
		spaces: 0

	StringQuotes:
		enabled: true
		style: double_quotes

	TrailingSemicolon:
		enabled: true

	TrailingZero:
		enabled: true

	UnnecessaryMantissa:
		enabled: true

	UnnecessaryParentReference:
		enabled: true

	UrlFormat:
		enabled: false

	UrlQuotes:
		enabled: true

	VariableForProperty:
		enabled: false

	VendorPrefixes:
		enabled: false
		identifier_list: base
		include: []
		exclude: []

	ZeroUnit:
		enabled: true

	Compass::*:
		enabled: false
